#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rabbitmq-java-client
Version  : 5.7.0
Release  : 1
URL      : https://github.com/rabbitmq/rabbitmq-java-client/archive/v5.7.0.tar.gz
Source0  : https://github.com/rabbitmq/rabbitmq-java-client/archive/v5.7.0.tar.gz
Source1  : https://github.com/DeadZen/goldrush/archive/0.2.0.tar.gz
Source2  : https://github.com/inaka/elvis.mk/archive/1.0.0.tar.gz
Source3  : https://github.com/rabbitmq/rabbitmq-cli/archive/v3.7.15-beta.1.tar.gz
Source4  : https://github.com/rabbitmq/rabbitmq-codegen/archive/v3.7.14.tar.gz
Source5  : https://github.com/rabbitmq/rabbitmq-common/archive/v3.8.0-beta.4.tar.gz
Source6  : https://github.com/rabbitmq/rabbitmq-ct-helpers/archive/rabbitmq_v3_6_14.tar.gz
Source7  : https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.14/rabbitmq-server-generic-unix-3.7.14.tar.xz
Source8  : https://github.com/rebar/rebar/archive/2.6.4.tar.gz
Source9  : https://github.com/schlagert/syslog/archive/3.4.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause GPL-2.0 HPND MIT MPL-1.1 MPL-2.0 MPL-2.0-no-copyleft-exception
Requires: rabbitmq-java-client-data = %{version}-%{release}
Requires: rabbitmq-java-client-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : maven-dep
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : rabbitmq-java-client-dep
Patch1: 0001-disable-the-automatic-test-cluster-setup.patch

%description
Put your EZs here and use rabbitmq-plugins to enable them.

%package data
Summary: data components for the rabbitmq-java-client package.
Group: Data

%description data
data components for the rabbitmq-java-client package.


%package license
Summary: license components for the rabbitmq-java-client package.
Group: Default

%description license
license components for the rabbitmq-java-client package.


%prep
%setup -q -n rabbitmq-java-client-5.7.0
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 7
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 6
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 4
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 3
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 5
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 1
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 2
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 8
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 9
mkdir -p deps/rabbit/
cp -r %{_topdir}/BUILD/rabbitmq_server-3.7.14/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbit/
mkdir -p deps/rabbitmq_ct_helpers/
cp -r %{_topdir}/BUILD/rabbitmq-ct-helpers-rabbitmq_v3_6_14/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbitmq_ct_helpers/
mkdir -p deps/rabbitmq_codegen
cp -r %{_topdir}/BUILD/rabbitmq-codegen-3.7.14/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbitmq_codegen
mkdir -p deps/rabbitmq_cli
cp -r %{_topdir}/BUILD/rabbitmq-cli-3.7.15-beta.1/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbitmq_cli
mkdir -p deps/rabbit_common
cp -r %{_topdir}/BUILD/rabbitmq-common-3.8.0-beta.4/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbit_common
mkdir -p deps/goldrush
cp -r %{_topdir}/BUILD/goldrush-0.2.0/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/goldrush
mkdir -p deps/elvis_mk
cp -r %{_topdir}/BUILD/elvis.mk-1.0.0/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/elvis_mk
mkdir -p deps/rabbit/.erlang.mk/rebar
cp -r %{_topdir}/BUILD/rebar-2.6.4/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbit/.erlang.mk/rebar
mkdir -p deps/syslog
cp -r %{_topdir}/BUILD/syslog-3.4.5/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/syslog
%patch1 -p1

%build
## build_prepend content
mkdir -p /builddir/.m2
cp -r /usr/share/apache-maven/.m2/* /builddir/.m2/
cp -r /usr/share/rabbitmq-java-client/.m2/* /builddir/.m2/
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557804538
export LDFLAGS="${LDFLAGS} -fno-lto"
make  %{?_smp_mflags} all && (make %{?_smp_mflags} tests || :)


%install
export SOURCE_DATE_EPOCH=1557804538
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rabbitmq-java-client
cp LICENSE-APACHE2 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/LICENSE-APACHE2
cp LICENSE-GPL2 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/LICENSE-GPL2
cp LICENSE-MPL-RabbitMQ %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/LICENSE-MPL-RabbitMQ
cp deps/elvis_mk/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_elvis_mk_LICENSE
cp deps/goldrush/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_goldrush_LICENSE
cp deps/rabbit/.erlang.mk/rebar/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_.erlang.mk_rebar_LICENSE
cp deps/rabbit/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE
cp deps/rabbit/LICENSE-APACHE2 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2
cp deps/rabbit/LICENSE-APACHE2-ExplorerCanvas %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2-ExplorerCanvas
cp deps/rabbit/LICENSE-APACHE2-excanvas %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2-excanvas
cp deps/rabbit/LICENSE-APL2-Stomp-Websocket %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APL2-Stomp-Websocket
cp deps/rabbit/LICENSE-BSD-base64js %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-BSD-base64js
cp deps/rabbit/LICENSE-BSD-recon %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-BSD-recon
cp deps/rabbit/LICENSE-ISC-cowboy %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-ISC-cowboy
cp deps/rabbit/LICENSE-MIT-EJS %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-EJS
cp deps/rabbit/LICENSE-MIT-EJS10 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-EJS10
cp deps/rabbit/LICENSE-MIT-Erlware-Commons %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Erlware-Commons
cp deps/rabbit/LICENSE-MIT-Flot %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Flot
cp deps/rabbit/LICENSE-MIT-Mochi %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Mochi
cp deps/rabbit/LICENSE-MIT-Sammy %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Sammy
cp deps/rabbit/LICENSE-MIT-Sammy060 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Sammy060
cp deps/rabbit/LICENSE-MIT-jQuery %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-jQuery
cp deps/rabbit/LICENSE-MIT-jQuery164 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-jQuery164
cp deps/rabbit/LICENSE-MPL-RabbitMQ %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MPL-RabbitMQ
cp deps/rabbit/LICENSE-MPL2 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MPL2
cp deps/rabbit/LICENSE-erlcloud %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-erlcloud
cp deps/rabbit/LICENSE-httpc_aws %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-httpc_aws
cp deps/rabbit/LICENSE-rabbitmq_aws %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-rabbitmq_aws
cp deps/rabbit_common/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE
cp deps/rabbit_common/LICENSE-BSD-recon %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-BSD-recon
cp deps/rabbit_common/LICENSE-MIT-Erlware-Commons %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MIT-Erlware-Commons
cp deps/rabbit_common/LICENSE-MIT-Mochi %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MIT-Mochi
cp deps/rabbit_common/LICENSE-MPL-RabbitMQ %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MPL-RabbitMQ
cp deps/rabbitmq_codegen/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_LICENSE
cp deps/rabbitmq_codegen/LICENSE-MPL-RabbitMQ %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_LICENSE-MPL-RabbitMQ
cp deps/rabbitmq_codegen/license_info %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_license_info
cp deps/syslog/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_syslog_LICENSE
:
## install_append content
mkdir -p %{buildroot}/usr/share/rabbitmq-java-client
cp -R target/*.jar %{buildroot}/usr/share/rabbitmq-java-client/
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/rabbitmq-java-client/amqp-client-5.7.0-sources.jar
/usr/share/rabbitmq-java-client/amqp-client-5.7.0.jar

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rabbitmq-java-client/LICENSE-APACHE2
/usr/share/package-licenses/rabbitmq-java-client/LICENSE-GPL2
/usr/share/package-licenses/rabbitmq-java-client/LICENSE-MPL-RabbitMQ
/usr/share/package-licenses/rabbitmq-java-client/deps_elvis_mk_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_goldrush_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_.erlang.mk_rebar_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2-ExplorerCanvas
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2-excanvas
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APL2-Stomp-Websocket
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-BSD-base64js
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-BSD-recon
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-ISC-cowboy
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-EJS
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-EJS10
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Erlware-Commons
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Flot
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Mochi
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Sammy
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Sammy060
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-jQuery
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-jQuery164
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MPL-RabbitMQ
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MPL2
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-erlcloud
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-httpc_aws
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-rabbitmq_aws
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-BSD-recon
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MIT-Erlware-Commons
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MIT-Mochi
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MPL-RabbitMQ
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_LICENSE-MPL-RabbitMQ
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_license_info
/usr/share/package-licenses/rabbitmq-java-client/deps_syslog_LICENSE
