#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rabbitmq-java-client
Version  : 5.7.0
Release  : 3
URL      : https://github.com/rabbitmq/rabbitmq-java-client/archive/v5.7.0.tar.gz
Source0  : https://github.com/rabbitmq/rabbitmq-java-client/archive/v5.7.0.tar.gz
Source1  : https://github.com/DeadZen/goldrush/archive/0.2.0.tar.gz
Source2  : https://github.com/inaka/elvis.mk/archive/1.0.0.tar.gz
Source3  : https://github.com/rabbitmq/rabbitmq-cli/archive/v3.7.15-beta.1.tar.gz
Source4  : https://github.com/rabbitmq/rabbitmq-codegen/archive/v3.7.14.tar.gz
Source5  : https://github.com/rabbitmq/rabbitmq-common/archive/v3.8.0-beta.4.tar.gz
Source6  : https://github.com/rabbitmq/rabbitmq-ct-helpers/archive/rabbitmq_v3_6_14.tar.gz
Source7  : https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.14/rabbitmq-server-generic-unix-3.7.14.tar.xz
Source8  : https://github.com/rebar/rebar/archive/2.6.4.tar.gz
Source9  : https://github.com/schlagert/syslog/archive/3.4.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause GPL-2.0 HPND MIT MPL-1.1 MPL-2.0 MPL-2.0-no-copyleft-exception
Requires: rabbitmq-java-client-data = %{version}-%{release}
Requires: rabbitmq-java-client-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : mvn-HdrHistogram
BuildRequires : mvn-LatencyUtils
BuildRequires : mvn-aether-core
BuildRequires : mvn-ant
BuildRequires : mvn-ant-launcher
BuildRequires : mvn-apache
BuildRequires : mvn-asm
BuildRequires : mvn-assertj-core
BuildRequires : mvn-assertj-parent-pom
BuildRequires : mvn-awaitility
BuildRequires : mvn-backport-util-concurrent
BuildRequires : mvn-beanshell
BuildRequires : mvn-biz.aQute.bndlib
BuildRequires : mvn-build-helper-maven-plugin
BuildRequires : mvn-byte-buddy
BuildRequires : mvn-classworlds
BuildRequires : mvn-commons-cli
BuildRequires : mvn-commons-codec
BuildRequires : mvn-commons-collections
BuildRequires : mvn-commons-compress
BuildRequires : mvn-commons-io
BuildRequires : mvn-commons-lang
BuildRequires : mvn-commons-logging
BuildRequires : mvn-commons-parent
BuildRequires : mvn-doxia
BuildRequires : mvn-doxia-sitetools
BuildRequires : mvn-easymock
BuildRequires : mvn-felix
BuildRequires : mvn-file-management
BuildRequires : mvn-gmaven
BuildRequires : mvn-gossip
BuildRequires : mvn-groovy
BuildRequires : mvn-guava
BuildRequires : mvn-guice
BuildRequires : mvn-hamcrest
BuildRequires : mvn-httpcomponents-client
BuildRequires : mvn-httpcomponents-core
BuildRequires : mvn-jackson-annotations
BuildRequires : mvn-jackson-bom
BuildRequires : mvn-jackson-core
BuildRequires : mvn-jackson-databind
BuildRequires : mvn-jackson-parent
BuildRequires : mvn-jansi
BuildRequires : mvn-jdom
BuildRequires : mvn-jline
BuildRequires : mvn-jsr305
BuildRequires : mvn-junit
BuildRequires : mvn-junit5
BuildRequires : mvn-keytool
BuildRequires : mvn-logback-classic
BuildRequires : mvn-logback-core
BuildRequires : mvn-maven
BuildRequires : mvn-maven-aether-provider
BuildRequires : mvn-maven-archiver
BuildRequires : mvn-maven-artifact
BuildRequires : mvn-maven-artifact-manager
BuildRequires : mvn-maven-bundle-plugin
BuildRequires : mvn-maven-compat
BuildRequires : mvn-maven-compiler-plugin
BuildRequires : mvn-maven-core
BuildRequires : mvn-maven-error-diagnostics
BuildRequires : mvn-maven-filtering
BuildRequires : mvn-maven-jar-plugin
BuildRequires : mvn-maven-model
BuildRequires : mvn-maven-model-builder
BuildRequires : mvn-maven-monitor
BuildRequires : mvn-maven-packagecloud-wagon
BuildRequires : mvn-maven-parent
BuildRequires : mvn-maven-plugin-api
BuildRequires : mvn-maven-plugin-descriptor
BuildRequires : mvn-maven-plugin-parameter-documenter
BuildRequires : mvn-maven-plugin-registry
BuildRequires : mvn-maven-plugin-tools
BuildRequires : mvn-maven-plugins
BuildRequires : mvn-maven-profile
BuildRequires : mvn-maven-project
BuildRequires : mvn-maven-reporting-api
BuildRequires : mvn-maven-repository-metadata
BuildRequires : mvn-maven-resources-plugin
BuildRequires : mvn-maven-settings
BuildRequires : mvn-maven-settings-builder
BuildRequires : mvn-maven-shared
BuildRequires : mvn-maven-shared-utils
BuildRequires : mvn-maven-source-plugin
BuildRequires : mvn-maven-surefire
BuildRequires : mvn-maven-toolchain
BuildRequires : mvn-metrics
BuildRequires : mvn-micrometer
BuildRequires : mvn-mockito-core
BuildRequires : mvn-mojo-parent
BuildRequires : mvn-mvnplugins
BuildRequires : mvn-objenesis
BuildRequires : mvn-org.apache.felix.bundlerepository
BuildRequires : mvn-org.osgi.compendium
BuildRequires : mvn-org.osgi.core
BuildRequires : mvn-oro
BuildRequires : mvn-oss-parents
BuildRequires : mvn-ow2
BuildRequires : mvn-plexus
BuildRequires : mvn-plexus-archiver
BuildRequires : mvn-plexus-build-api
BuildRequires : mvn-plexus-cipher
BuildRequires : mvn-plexus-classworlds
BuildRequires : mvn-plexus-compiler
BuildRequires : mvn-plexus-containers
BuildRequires : mvn-plexus-i18n
BuildRequires : mvn-plexus-interactivity
BuildRequires : mvn-plexus-interpolation
BuildRequires : mvn-plexus-io
BuildRequires : mvn-plexus-languages
BuildRequires : mvn-plexus-utils
BuildRequires : mvn-plexus-velocity
BuildRequires : mvn-qdox
BuildRequires : mvn-sisu
BuildRequires : mvn-sisu-guice
BuildRequires : mvn-slf4j
BuildRequires : mvn-snappy
BuildRequires : mvn-sonatype-aether
BuildRequires : mvn-sonatype-plexus-sec-dispatcher
BuildRequires : mvn-velocity
BuildRequires : mvn-wagon
BuildRequires : mvn-xz
BuildRequires : openjdk
BuildRequires : openjdk-dev
Patch1: 0001-disable-the-automatic-test-cluster-setup.patch
Patch2: 0002-enable-compilation-in-offline-mode.patch

%description
Put your EZs here and use rabbitmq-plugins to enable them.

%package data
Summary: data components for the rabbitmq-java-client package.
Group: Data

%description data
data components for the rabbitmq-java-client package.


%package license
Summary: license components for the rabbitmq-java-client package.
Group: Default

%description license
license components for the rabbitmq-java-client package.


%prep
%setup -q -n rabbitmq-java-client-5.7.0
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 7
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 6
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 4
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 3
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 5
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 1
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 2
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 8
cd ..
%setup -q -T -D -n rabbitmq-java-client-5.7.0 -b 9
mkdir -p deps/rabbit/
cp -r %{_topdir}/BUILD/rabbitmq_server-3.7.14/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbit/
mkdir -p deps/rabbitmq_ct_helpers/
cp -r %{_topdir}/BUILD/rabbitmq-ct-helpers-rabbitmq_v3_6_14/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbitmq_ct_helpers/
mkdir -p deps/rabbitmq_codegen
cp -r %{_topdir}/BUILD/rabbitmq-codegen-3.7.14/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbitmq_codegen
mkdir -p deps/rabbitmq_cli
cp -r %{_topdir}/BUILD/rabbitmq-cli-3.7.15-beta.1/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbitmq_cli
mkdir -p deps/rabbit_common
cp -r %{_topdir}/BUILD/rabbitmq-common-3.8.0-beta.4/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbit_common
mkdir -p deps/goldrush
cp -r %{_topdir}/BUILD/goldrush-0.2.0/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/goldrush
mkdir -p deps/elvis_mk
cp -r %{_topdir}/BUILD/elvis.mk-1.0.0/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/elvis_mk
mkdir -p deps/rabbit/.erlang.mk/rebar
cp -r %{_topdir}/BUILD/rebar-2.6.4/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/rabbit/.erlang.mk/rebar
mkdir -p deps/syslog
cp -r %{_topdir}/BUILD/syslog-3.4.5/* %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/syslog
%patch1 -p1
%patch2 -p1

%build
## build_prepend content
cp -r /usr/share/java/.m2/* /builddir/.m2
cp -r %{_topdir}/BUILD/rabbitmq-java-client-5.7.0/deps/* /builddir/.m2
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568350564
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags} all && (make %{?_smp_mflags} tests || :)


%install
export SOURCE_DATE_EPOCH=1568350564
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rabbitmq-java-client
cp LICENSE-APACHE2 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/LICENSE-APACHE2
cp LICENSE-GPL2 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/LICENSE-GPL2
cp LICENSE-MPL-RabbitMQ %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/LICENSE-MPL-RabbitMQ
cp deps/elvis_mk/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_elvis_mk_LICENSE
cp deps/goldrush/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_goldrush_LICENSE
cp deps/rabbit/.erlang.mk/rebar/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_.erlang.mk_rebar_LICENSE
cp deps/rabbit/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE
cp deps/rabbit/LICENSE-APACHE2 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2
cp deps/rabbit/LICENSE-APACHE2-ExplorerCanvas %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2-ExplorerCanvas
cp deps/rabbit/LICENSE-APACHE2-excanvas %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2-excanvas
cp deps/rabbit/LICENSE-APL2-Stomp-Websocket %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APL2-Stomp-Websocket
cp deps/rabbit/LICENSE-BSD-base64js %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-BSD-base64js
cp deps/rabbit/LICENSE-BSD-recon %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-BSD-recon
cp deps/rabbit/LICENSE-ISC-cowboy %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-ISC-cowboy
cp deps/rabbit/LICENSE-MIT-EJS %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-EJS
cp deps/rabbit/LICENSE-MIT-EJS10 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-EJS10
cp deps/rabbit/LICENSE-MIT-Erlware-Commons %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Erlware-Commons
cp deps/rabbit/LICENSE-MIT-Flot %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Flot
cp deps/rabbit/LICENSE-MIT-Mochi %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Mochi
cp deps/rabbit/LICENSE-MIT-Sammy %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Sammy
cp deps/rabbit/LICENSE-MIT-Sammy060 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Sammy060
cp deps/rabbit/LICENSE-MIT-jQuery %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-jQuery
cp deps/rabbit/LICENSE-MIT-jQuery164 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-jQuery164
cp deps/rabbit/LICENSE-MPL-RabbitMQ %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MPL-RabbitMQ
cp deps/rabbit/LICENSE-MPL2 %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MPL2
cp deps/rabbit/LICENSE-erlcloud %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-erlcloud
cp deps/rabbit/LICENSE-httpc_aws %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-httpc_aws
cp deps/rabbit/LICENSE-rabbitmq_aws %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-rabbitmq_aws
cp deps/rabbit_common/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE
cp deps/rabbit_common/LICENSE-BSD-recon %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-BSD-recon
cp deps/rabbit_common/LICENSE-MIT-Erlware-Commons %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MIT-Erlware-Commons
cp deps/rabbit_common/LICENSE-MIT-Mochi %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MIT-Mochi
cp deps/rabbit_common/LICENSE-MPL-RabbitMQ %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MPL-RabbitMQ
cp deps/rabbitmq_codegen/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_LICENSE
cp deps/rabbitmq_codegen/LICENSE-MPL-RabbitMQ %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_LICENSE-MPL-RabbitMQ
cp deps/rabbitmq_codegen/license_info %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_license_info
cp deps/syslog/LICENSE %{buildroot}/usr/share/package-licenses/rabbitmq-java-client/deps_syslog_LICENSE
:
## install_append content
mkdir -p %{buildroot}/usr/share/rabbitmq-java-client
cp -R target/*.jar %{buildroot}/usr/share/rabbitmq-java-client/
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/rabbitmq-java-client/amqp-client-5.7.0-sources.jar
/usr/share/rabbitmq-java-client/amqp-client-5.7.0.jar

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rabbitmq-java-client/LICENSE-APACHE2
/usr/share/package-licenses/rabbitmq-java-client/LICENSE-GPL2
/usr/share/package-licenses/rabbitmq-java-client/LICENSE-MPL-RabbitMQ
/usr/share/package-licenses/rabbitmq-java-client/deps_elvis_mk_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_goldrush_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_.erlang.mk_rebar_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2-ExplorerCanvas
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APACHE2-excanvas
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-APL2-Stomp-Websocket
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-BSD-base64js
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-BSD-recon
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-ISC-cowboy
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-EJS
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-EJS10
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Erlware-Commons
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Flot
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Mochi
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Sammy
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-Sammy060
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-jQuery
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MIT-jQuery164
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MPL-RabbitMQ
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-MPL2
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-erlcloud
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-httpc_aws
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_LICENSE-rabbitmq_aws
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-BSD-recon
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MIT-Erlware-Commons
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MIT-Mochi
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbit_common_LICENSE-MPL-RabbitMQ
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_LICENSE
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_LICENSE-MPL-RabbitMQ
/usr/share/package-licenses/rabbitmq-java-client/deps_rabbitmq_codegen_license_info
/usr/share/package-licenses/rabbitmq-java-client/deps_syslog_LICENSE
